core/urls.py
from django.urls import path

from .views import ( ItemDetailView, CheckoutView, HomeView, OrderSummaryView, add_to_cart, register_request, remove_from_cart, remove_single_item_from_cart, PaymentView, otp_check, login_request,  logout, seller, profile, UploadItem, update_otp_check, update_profile, order_history, seller_items, seller_items, search)

app_name = 'core'

urlpatterns = [
    path('otp/', otp_check, name='otp'),
    path('seller/', seller, name='seller'),
    path('search/', search, name='search'),
    path('signout/', logout, name='signout'),
    path('profile/', profile, name='profile'),
    path('upload/', UploadItem, name='upload'),
    path('', HomeView.as_view(), name='start'),
    path('signin/', login_request, name='signin'),
    path('register/', register_request, name='register'),
    path('updateotp/', update_otp_check, name='updateotp'),
    path('seller_items/', seller_items, name='seller_items'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order_history/', order_history, name='order_history'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('update_profile/', update_profile, name='update_profile'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.db import models
from django.contrib.auth.models import User as off_user

class User(models.Model):
    username = models.CharField(max_length=150, primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=500)
    is_seller = models.BooleanField(default =False)
    is_verified = models.BooleanField(default =False)
    is_pdf_uploaded = models.BooleanField(default=False)
    pdf_file = models.FileField(upload_to='static/', null=True, blank=True)
    user = models.OneToOneField(off_user, on_delete=models.CASCADE)
    USERNAME_FIELD = 'username'

    def register(self):
        self.save()
    
    @staticmethod
    def get_customer_by_email(email):
        try:
            return User.objects.get(email=email)
        except:
            return False

    def get_is_seller(self):
        return str(self.is_seller)

    def get_is_verified(self):
        return self.is_verified

    @staticmethod
    def get_customer_by_id(ids):
        return User.objects.get(username=ids)

    @staticmethod
    def get_customer_by_session_id(ids):
        return User.objects.get(id__in=ids)

    def isExists(self):
        if User.objects.filter(username = self.username):
            return True
        return  False

CATEGORY_CHOICES = ( ('SW', 'Smart Watches'), ('AG', 'Audio Gear'), ('VA', 'Voice Assistants'), ('P', 'Phones'), ('L', 'Laptops'), ('C', 'Cameras') )

LABEL_CHOICES = ( ('P', 'New'), ('S', 'Few Left'), ('D', 'Limited Period Offer'))

ADDRESS_CHOICES = ( ('S', 'Shipping') ,)


class UserProfile(models.Model):
    user = models.OneToOneField(
    settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.CharField(max_length=50)
    description = models.TextField()
    image = models.ImageField(upload_to='static/')
    image2 = models.ImageField(upload_to='static/', null=True)
    seller = models.ForeignKey(User, on_delete = models.CASCADE)
    
    def __str__(self):
        return self.title

    @staticmethod
    def get_item_by_slug(slug):
        return Item.objects.get(slug=slug)
    
    def get_slug(self):
        return self.slug

    def get_absolute_url(self):
        return reverse("core:product", kwargs={ 'slug': self.slug })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={ 'slug': self.slug })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={ 'slug': self.slug })

    @staticmethod
    def get_all_products_by_id(category_id):
        if category_id:
            return Item.objects.filter(category = category_id)
        else:
            return Item.objects.all()



class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey( 'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey( 'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    received = models.BooleanField(default=False)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    
    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Our Shop Page</title>
    <link rel="icon" type="image/x-icon" href="/static/assets/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <link href="/static/css/styles.css" rel="stylesheet" />
    {% include "navbar.html" %}
    <body>
        <div class="mt-5 pt-4">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible show" role="alert">
                {{ message }}
                <button type="button" class="close-button" onclick="this.parentElement.style.display='none';"  aria-label="Dismiss alert">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        {% block content %}
        {% endblock content %} 
        {% block extra_body %}
        {% endblock %}
        {% block extra_scripts %}
        {% endblock extra_scripts %}
    </body>
</html>

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<main >
    <div class="container wow fadeIn">
        <h2 class="my-5 h2 text-center">Checkout form</h2>
        <div class="row">
            <div class="col-md-8 mb-4">
                <div class="card">
                    <form method="POST" class="card-body" id ="payment_form">
                        {% csrf_token %}
                        <h3>Shipping address</h3>
                        <div class='hideable_shipping_form', id = 'hideable_shipping_form' >
                            <div class="md-form mb-5">
                                <label for="shipping_address" class="">Address*</label>
                                <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control' />
                            </div>
                            <div class="md-form mb-5">
                                <label for="shipping_address2" class="">Address 2 (optional)</label>
                                <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
                            </div>
                            <div class="row">
                                <div class="col-lg-4 col-md-12 mb-4">
                                    <label for="country">Country</label>
                                    {{ form.shipping_country |safe}}
                                    <div class="invalid-feedback">
                                        Please select a valid country.
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-6 mb-4">
                                    <label for="shipping_zip">Zip</label>
                                    <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                                    <div class="invalid-feedback">
                                        Zip code required.
                                    </div>
                                </div>
                            </div>
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                                <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
                            </div>
                        </div>
                        {% if default_shipping_address %}
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
                            <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|safe|truncatechars:10 }}</label>
                        </div>
                        {% endif %}
                        <hr>
                        <h3>Payment option</h3>
                        <div class="d-block my-3">
                            {% for value, name in form.fields.payment_option.choices %}
                            <div class="custom-control custom-radio">
                                <input id="{{ name |safe}}" name="payment_option" value="{{ value |safe}}" type="radio" class="custom-control-input" required>
                                <label class="custom-control-label" for="{{ name|safe }}">{{ name |safe}}</label>
                            </div>
                            {% endfor %}
                        </div>
                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
                    </form>
                </div>
            </div>
            <div class="col-md-4 mb-4">
                {% include "order_snippet.html" %}
            </div>
        </div>
    </div>
</main>
{% endblock content %}
{% block extra_scripts %}
<script>
    var hideable_shipping_form = document.getElementById("hideable_shipping_form");
    var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
    
    use_default_shipping.addEventListener('change', function() {
      if (this.checked) { document.getElementById('shipping_address').value = '{{default_shipping_address.street_address | safe }}'; document.getElementById('shipping_address2').value = '{{default_shipping_address.apartment_address | safe }}'; document.getElementById('id_shipping_country').value = '{{default_shipping_address.country | safe }}'; document.getElementById('shipping_zip').value = '{{default_shipping_address.zip | safe }}'.toString();} 
      else
       { document.getElementById("payment_form").reset();}
    })
</script>
{% endblock extra_scripts %}

templates/order_history.html
{% extends "base.html" %}
{% block head_title %}Seller MainPage {% endblock head_title %}
{% block content %}      
{% load crispy_forms_tags %}
<main>
    <div class="container">
        <section class="mb-4">
            <div class="row wow fadeIn">
                <div class="col-6 offset-3">
                    <h1> Hello {{request.user.username}} !! </h1>
                    <br>
                    {% if request.session.is_seller %}
                    <h1>
                    Sellers don't have an order history </h2>
                    {% else %}
                    {% if is_order %}
                    <div class="col-md-12 mb-4">
                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                            <span class="text-muted">Your Past Orders</span>
                            {% for object in all_orders %}
                            <span class="badge badge-secondary badge-pill">{{ order.items.count |safe}}</span>
                        </h4>
                        <ul class="list-group mb-3 z-depth-1">
                            {% for order_item in object.items.all %}
                            <li class="list-group-item d-flex justify-content-between lh-condensed">
                                <div>
                                    <h6 class="my-0">{{ order_item.quantity|safe }} x {{ order_item.item.title|safe}}</h6>
                                    <small class="text-muted">{{ order_item.item.description|safe}}</small>
                                </div>
                                <span class="text-muted">₹{{ order_item.get_final_price|safe }}</span>
                            </li>
                            {% endfor %}
                            <li class="list-group-item d-flex justify-content-between">
                                <span>Total (INR)</span>
                                <strong>₹{{ object.get_total|safe }}</strong>
                            </li>
                        </ul>
                    </div>
                    {% endfor %}
                    {% else %}
                    <h1> You don't have an order yet. </h1>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
        </section>
    </div>
</main>
{% endblock %}

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count |safe}}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                <h6 class="my-0">{{ order_item.quantity|safe }} x {{ order_item.item.title|safe}}</h6>
                <small class="text-muted">{{ order_item.item.description|safe}}</small>
                </div>
                <span class="text-muted">₹{{ order_item.get_final_price|safe }}</span>
            </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Total (INR)</span>
            <strong>₹{{ order.get_total|safe }}</strong>
        </li>
    </ul>
</div>

templates/order_summary.html
{% extends "base.html" %}
{% block content %}
<main>
    <div class="container">
        <div class="table-responsive text-nowrap">
            <h2>Order Summary</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Item title</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter|safe }}</th>
                        <td>{{ order_item.item.title|safe }}</td>
                        <td>{{ order_item.item.price |safe}}</td>
                        <td>
                            <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                            {{ order_item.quantity }}
                            <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
                        </td>
                        <td>
                            {% if order_item.item.discount_price %}
                            ₹{{ order_item.get_total_discount_item_price|safe }}
                            <span class="badge badge-primary">Saving ₹{{ order_item.get_amount_saved|safe }}</span>
                            {% else %}
                            ₹{{ order_item.get_total_item_price |safe}}
                            {% endif %}
                            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                            <i class="fas fa-trash float-right"></i>
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan='5'>Your cart is empty</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% if object.coupon %}
                    <tr>
                        <td colspan="4"><b>Coupon</b></td>
                        <td><b>-₹{{ object.coupon.amount|safe }}</b></td>
                    </tr>
                    {% endif %}
                    {% if object.get_total %}
                    <tr>
                        <td colspan="4"><b>Order Total</b></td>
                        <td><b>₹{{ object.get_total|safe }}</b></td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
                            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</main>
{% endblock content %}

templates/payment.html
{% extends "base.html" %}

{% block content %}
  <main >
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Payment</h2>
      <div class="row">
        <div class="col-md-12 mb-4">
          <div class="card">
            <div class="new-card-form">
              <form action="." method="post" class="stripe-form" id="stripe-form">
              {% csrf_token %}
              <div class="card-body" id="creditCard">
                <h3>Credit or debit card</h3>
                <hr>
                <div id="card-element" class="StripeElement StripeElement--empty"><div class="__PrivateStripeElement" ></div></div>
              </div>
              <div class="stripe-form-row">
                <center>
                  <button id="stripeBtn" class = "btn btn-primary btn-lg btn-block">Submit Payment</button>
                </center>
                <br>
              </div>
              <div id="card-errors" role="alert"></div>
              </form>
            </div>
          </div>
        </div>
        {% include "order_snippet.html" %}
      </div>
    </div>
  </main>

{% endblock content %}

{% block extra_scripts %}

<script src="https://js.stripe.com/v3/"></script>
<script nonce=""> 
  var stripe = Stripe('{{STRIPE_PUBLIC_KEY}}');
  var elements = stripe.elements();
  var style = {
    base: {
      color: '#32325d',
      fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
      fontSmoothing: 'antialiased',
      fontSize: '16px',
      '::placeholder': {
        color: '#aab7c4'
      }
    },
    invalid: {
      color: '#fa755a',
      iconColor: '#fa755a'
    }
  };

  var card = elements.create('card', {style: style});
  card.mount('#card-element');
  card.addEventListener('change', function(event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
  });
  var form = document.getElementById('stripe-form');
  form.addEventListener('submit', function(event) {
    event.preventDefault();
    stripe.createToken(card).then(function(result) {
      if (result.error) {
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        stripeTokenHandler(result.token);
      }
    });
  });

  function stripeTokenHandler(token) {
    var form = document.getElementById('stripe-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);
    form.submit();
  }
</script>

{% endblock extra_scripts %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <main>
    <div class="container">
      <h2>Request Refund</h2>
      <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
      </form>
    </div>
  </main>
{% endblock content %}

templates/search_item.html
{% extends "base.html" %} 
{% block content %} 
{% if request.session.User %}
   {% if request.session.is_seller %}
      <br> <br> <br> <br> <br> <center> <h1> You are a seller! </h1> 
      <a href='/seller/' class='btn btn-dark btn-lg'> Check your status.</a>
      </center>
   {%else%}
         <br> <center> <h1> You searched for ... </h1> </center>
      <section style="text-align: center;" class="text-center mb-4">
         <div class="row wow fadeIn">
            {% for item in object_list %}
               <div style="top: 100ch;" class="col-lg-3 col-md-6 mb-4">
                  <div style="margin-left: 10ch; size: 10ch; margin-top: -5ch;" class="card">
                     <div style="margin-left: 10%; size: 10ch;" class="view overlay">
                        <img style="align-content: center; size: 10ch;" src="{{ item.image.url }}" class="card-img-top">
                        <a href="{{ item.get_absolute_url }}">
                           <div class="mask rgba-white-slight"></div>
                        </a>
                     </div>
                     <div class="card-body text-center">
                        {% comment %} <a href="#" class="grey-text"> {% endcomment %}
                           <h5>{{ item.get_category_display }}</h5>
                        {% comment %} </a> {% endcomment %}
                        <h5>
                           <strong>
                           <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                           <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                           </a>
                           </strong>
                        </h5>
                        <h4 class="font-weight-bold blue-text">
                           <strong>₹
                           {% if item.discount_price %}
                           {{ item.discount_price }}
                           {% else %}
                           {{ item.price }}
                           {% endif %}
                           </strong>
                        </h4>
                     </div>
                  </div>
               </div>
            {% endfor %}
         </div>
      </section>
   {% endif %}
{% else %}
   <div class="container">
      <br> <br> <br> <br> <br> <center> <h1>Please Log In! </h1> 
         <a href='/' class='btn btn-dark btn-lg'>Home</a>
         </center>
   </div>
{% endif %}
</body>
</html>
{% endblock content %}

templates/seller.html
{% extends "base.html" %}
{% block head_title %}Seller MainPage {% endblock head_title %}
{% block content %}      
{% load crispy_forms_tags %}
<main>
    <div class="container">
        <section class="mb-4">
            <div class="row wow fadeIn">
                <div class="col-6 offset-3">
                    {% if request.session.is_seller %}
                    {% if request.session.is_verified %}
                    <h1> You are a verified seller. </h1>
                    <center>
                        <a href='/upload/' class='btn btn-dark btn-lg'> Upload Items</a>
                    </center>
                    {%else%}
                    {% if request.session.is_pdf_uploaded %}
                    <h1> You are yet to be verified... </h1>
                    {% else %}
                    <h1> Please upload a file </h1>
                    <form enctype="multipart/form-data" action="/seller/" method="post">
                        {% csrf_token %}
                        {{ seller_form |crispy|safe }}
                        <input hidden="" type='Text' name='username' value='{{request.user.username|safe}}'>
                        <br>
                        <button class="btn btn-primary" type="submit">Submit File</button>
                    </form>
                    {% endif %}
                    {% endif %}
                    {% else %}
                    <h1> Please register yourself as a seller! </h1>
                    {% endif %}
                </div>
            </div>
        </section>
    </div>
</main>
{% endblock %}

templates/seller_items.html
{% extends "base.html" %}
{% block head_title %}Seller MainPage {% endblock head_title %}
{% block content %} 
{% if is_seller %}
<br> 
<center>
    <h1> Your Products </h1>
</center>
<section style="text-align: center;" class="text-center mb-4">
    <div class="row wow fadeIn">
        {% for item in all_items %}
        <div style="top: 100ch;" class="col-lg-3 col-md-6 mb-4">
            <div style="margin-left: 10ch; size: 10ch; margin-top: -5ch;" class="card">
                <div style="margin-left: 10%; size: 10ch;" class="view overlay">
                    <img style="align-content: center; size: 10ch;" src="{{ item.image.url }}" class="card-img-top">
                    <a href="{{ item.get_absolute_url }}">
                        <div class="mask rgba-white-slight"></div>
                    </a>
                </div>
                <div class="card-body text-center">
                    <a href="" class="grey-text">
                        <h5>{{ item.get_category_display }}</h5>
                    </a>
                    <h5> <strong>
                        <a href="#" class="dark-grey-text">{{ item.title }}
                        <span class="badge badge-pill">{{item.get_label_display|safe}}</span>
                        </a>
                        </strong> 
                    </h5>
                    <h4 class="font-weight-bold blue-text"> <strong>₹
                        {% if item.discount_price %}
                        {{ item.discount_price }}
                        {% else %}
                        {{ item.price }}
                        {% endif %}
                        </strong> 
                    </h4>
                    <p class="lead font-weight-bold">Description</p>
                    <p>{{ item.description|safe }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
{% else %}
<br> <br> <br> <br> 
<center>
    <h1> Oops. . . You are not a seller. </h1>
</center>
{% endif %}
{% endblock %}

templates/signin.html
{% extends "base.html" %}
{% block head_title %}Login {% endblock head_title %}
{% block content %}      
{% load crispy_forms_tags %}
<main>
    <div class="container">
        <section class="mb-4">
            <div class="row wow fadeIn">
                <div class="col-6 offset-3">
                    {% if request.user.is_authenticated %}
                    <h1>You are already signed in.</h1>
                    {% else %}
                    <h1>Sign In</h1>
                    <p>
                        If you have not created an account yet, then please
                        <a href="/register/">Sign Up</a> first.
                    </p>
                    <form action="/signin/" method="post">
                        {% csrf_token %}
                        {{ login_form|crispy }}
                        <br>  
                        <button class="btn btn-primary" type="submit">Login</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </section>
    </div>
</main>
{% endblock %}